# -*- coding: utf-8 -*-
"""Trent Hutten_cba.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XwQMywyc6Jd0dBEJQOeI4m1Z1Y__wtOu
"""

#@title Default title text
import pandas as pd
import math

dataT=pd.read_csv('/content/drive/MyDrive/262-CBA.csv')
print(dataT)

discountRate=0.05
discountFactor=[0,0,0,0]
for year in dataT['years']:
  discountFactor[year]=1/math.pow((1+discountRate),year)

dataT['discountFactor']=[round(num,2) for num in discountFactor]
print (dataT)

NetBC=[0,0,0,0]
for year in dataT['years']:
  NetBC[year]=dataT['developmentCost'][year]+dataT['operationalCost'][year]+dataT['valueOfBenefits'][year]

dataT['NetBC']=NetBC
print (dataT)

NPV=[0,0,0,0]

for year in dataT['years']:
  NPV[year]=dataT['NetBC'][year]*dataT['discountFactor'][year]

dataT['NPV']=[round(num,2)for num in NPV]
print (dataT)